language: node_js

node_js: 8.12.0

branches:
  only:
    - master

cache:
  bundler: true
  yarn: true

install: npm install

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${ACCESS_TOKEN} # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master