language: node_js

node_js: 12.18.3

branches:
  only:
    - master

cache:
  bundler: true
  yarn: true

install: yarn

script: yarn build

deploy:
  local-dir: './dist'
  provider: pages
  skip_cleanup: true
  github_token: ${ACCESS_TOKEN} # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  keep_history: true
  on:
    branch: master