name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install 
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
    
